name: .NET Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build .NET project
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore --configuration Release

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Send Discord Notification
        run: |
          STATUS="${{ needs.build.result }}"
          echo "Build status is $STATUS"
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \":bell: PR build finished with status: **$STATUS**\"}" \
            ${{ https://discord.com/api/webhooks/1414125419610771466/Xkb9ADuwivDV3vwW0fl-pjpA_bSoq7GRFHfhTucFBAsoAx7TFNW7XPGArLLQESICpfvL Här är hook till alla att kopiera }}